# Generated by Django 5.2.2 on 2025-06-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
