# Generated by Django 5.2.2 on 2025-06-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhighlight',
            name='event',
        ),
        migrations.RenameField(
            model_name='eventimage',
            old_name='image_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='highlights',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventAmenity',
        ),
        migrations.DeleteModel(
            name='EventHighlight',
        ),
    ]
