# Generated by Django 5.2.2 on 2025-06-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
