# Generated by Django 5.2.2 on 2025-06-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='image_file',
        ),
    ]
