# Generated by Django 5.2.2 on 2025-06-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0002_remove_eventhighlight_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/gallery/'),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
