# Generated by Django 5.2.2 on 2025-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0002_remove_event_image_remove_eventimage_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/gallery/'),
        ),
    ]
