# Generated by Django 5.2.2 on 2025-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0002_remove_activity_image_activity_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginentry',
            name='password',
            field=models.CharField(default='default123', max_length=10),
            preserve_default=False,
        ),
    ]
