# Generated by Django 5.2.2 on 2025-06-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0003_loginentry_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='loginentry',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
