# Generated by Django 5.2.2 on 2025-06-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0004_alter_loginentry_email_alter_loginentry_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityDetails',
        ),
    ]
