# Generated by Django 5.2.2 on 2025-06-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0004_bookingdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingDetails',
        ),
    ]
