# Generated by Django 5.2.2 on 2025-09-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0005_delete_bookingdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginEntry',
        ),
    ]
