# Generated by Django 5.2.2 on 2025-09-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0007_contactmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
    ]
