# Generated by Django 5.2.2 on 2025-09-09 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0008_remove_contactmessage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('guests', models.PositiveIntegerField()),
                ('specialRequests', models.TextField(blank=True)),
                ('userId', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app3monkeys.event')),
            ],
        ),
    ]
