# Generated by Django 5.2.2 on 2025-09-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0010_event_extra_images_event_faq_event_heading_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDetails',
        ),
    ]
