# Generated by Django 5.2.2 on 2025-09-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0011_delete_eventdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='extra_images',
        ),
        migrations.RemoveField(
            model_name='event',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='event',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='event',
            name='info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_map',
        ),
        migrations.RemoveField(
            model_name='event',
            name='passes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='performers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='event',
            name='safety_guidelines',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='event',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_includes',
        ),
    ]
