# Generated by Django 5.2.2 on 2025-09-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0013_event_extra_images_event_faq_event_heading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='extra_images',
            new_name='images',
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app3monkeys.event'),
        ),
    ]
