# Generated by Django 5.2.2 on 2025-09-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0018_alter_event_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
