# Generated by Django 5.2.2 on 2025-09-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0020_alter_activity_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
