# Generated by Django 5.2.2 on 2025-09-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0021_alter_activity_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='faq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
