# Generated by Django 5.2.2 on 2025-09-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0022_alter_activity_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='faq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
