# Generated by Django 5.2.2 on 2025-09-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0023_alter_event_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='image_url',
        ),
    ]
