# Generated by Django 5.2.2 on 2025-09-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0025_booknow_event_delete_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknow',
            name='event',
        ),
    ]
