# Generated by Django 5.2.2 on 2025-09-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0026_remove_booknow_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app3monkeys.event'),
            preserve_default=False,
        ),
    ]
