# Generated by Django 5.2.2 on 2025-09-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0028_alter_booknow_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknow',
            name='event',
        ),
    ]
