# Generated by Django 5.2.2 on 2025-09-23 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0030_booknow_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app3monkeys.activity'),
        ),
    ]
