# Generated by Django 5.2.2 on 2025-09-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0031_booknow_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
    ]
