# Generated by Django 5.2.2 on 2025-09-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0033_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='name',
            new_name='user',
        ),
    ]
