# Generated by Django 5.2.2 on 2025-09-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0034_rename_name_userdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user',
            new_name='name',
        ),
    ]
