# Generated by Django 5.2.2 on 2025-09-29 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0035_rename_user_userdetails_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='first_name',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='first_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='last_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
