# Generated by Django 5.2.2 on 2025-09-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0036_remove_userdetails_name_userdetails_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='last_name',
        ),
    ]
