# Generated by Django 5.2.2 on 2025-09-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0038_userdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
