# Generated by Django 5.2.2 on 2025-09-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3monkeys', '0040_remove_userdetails_name_userdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
